org: jorgemelgarejo
service: api-rockies  # Cambié el nombre del servicio a api-rockies

provider:
  name: aws
  runtime: nodejs18.x  # Usamos Node.js
  region: us-east-1
  role: arn:aws:iam::232690452415:role/LabRole
  stage: ${opt:stage, 'dev'}

package:
  individually: true
  include:
    - dist/apis/**  # Incluir todos los archivos dentro de dist/apis/
    - dist/utils/**  # Incluir todos los archivos dentro de dist/utils/

functions:
  CreateRockie:
    handler: dist/apis/CreateRockie.lambda_handler  # Cambié a CreateRockie
    memorySize: 512
    timeout: 30
    environment:
      VALIDATE_FUNCTION_NAME: ${self:custom.validateTokenFunction}
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: rockies
          method: post
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.body
                }

  GetRockie:
    handler: dist/apis/GetRockie.lambda_handler  # Cambié a GetRockie
    memorySize: 512
    timeout: 30
    environment:
      VALIDATE_FUNCTION_NAME: ${self:custom.validateTokenFunction}
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: rockies
          method: get
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  }
                }

  UpdateRockie:
    handler: dist/apis/UpdateRockie.lambda_handler  # Cambié a UpdateRockie
    memorySize: 512
    timeout: 30
    environment:
      VALIDATE_FUNCTION_NAME: ${self:custom.validateTokenFunction}
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: rockies
          method: put
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.body
                }

  DeleteRockie:
    handler: dist/apis/DeleteRockie.lambda_handler  # Cambié a DeleteRockie
    memorySize: 512
    timeout: 30
    environment:
      VALIDATE_FUNCTION_NAME: ${self:custom.validateTokenFunction}
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: rockies
          method: delete
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  }
                }

custom:
  validateTokenFunction: api-security-${self:provider.stage}-ValidateAccessToken
